config/routes.rb
Debita46::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users 
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  root :to => 'home#dashboard'
  
  match 'raise_exception' => 'home#raise_exception', :as => :raise_exception 
  
  resources :terms   
  resources :enrollments
  resources :subjects do
    resources :courses 
    resources :subject_teaching_assignments
    resources :subject_registrations 
  end
  
  resources :courses do 
    resources :course_teaching_assignments
    resources :course_registrations
    resources :projects
    resources :groups
  end
  
  resources :projects
  resources :project_submissions
  resources :project_submissions do 
    resources :pictures
  end
  resources :user do 
    resources :project_submissions
  end
  
  resources :groups do 
    resources :group_memberships
  end
  resources :group_memberships
  
=begin
  CREATE SUBJECT, TERM_based
=end

  match 'select_term_to_create_subject' => 'terms#select_term_to_create_subject', :as => :select_term_to_create_subject
  match 'execute_close_term' => 'terms#execute_close_term', :as => :execute_close_term, :method => :post 
  match 'closed_terms' => 'terms#closed_terms', :as => :closed_terms
  
  
  match 'active_subjects_management' => "subjects#active_subjects_management", :as => :active_subjects_management
  match 'passive_subjects_management' => "subjects#passive_subjects_management", :as => :passive_subjects_management
  match 'duplicate_active_subject/:subject_id' => "subjects#duplicate_active_subject" , :as => :duplicate_active_subject
  match 'duplicate_passive_subject/:subject_id' => "subjects#duplicate_passive_subject" , :as => :duplicate_passive_subject
  
  match 'execute_duplicate_subject' => "subjects#execute_duplicate_subject" , :as => :execute_duplicate_subject, :method => :post 
  match 'close_subject' => "subjects#close_subject", :as => :close_subject, :method => :post 
  match 'recover_subject' => "subjects#recover_subject", :as => :recover_subject, :method => :post 
  
  match 'new_subject_teaching_assignment' => "subjects#new_subject_teaching_assignment", :as => :new_subject_teaching_assignment
  match 'pick_subject_for_course_teaching_assignment' => "courses#pick_subject_for_course_teaching_assignment", :as => :pick_subject_for_course_teaching_assignment
  match 'new_course_teaching_assignment/:subject_id' => "courses#new_course_teaching_assignment", :as => :new_course_teaching_assignment
  
  match 'select_course_for_grade_summary' => "courses#select_course_for_grade_summary", :as => :select_course_for_grade_summary 
  match 'show_student_grades_for_course/:course_id' => "courses#show_student_grades_for_course", :as => :show_student_grades_for_course 
  match 'show_project_grading_details/project/:project_id/student/:student_id' => "courses#show_project_grading_details", :as => :show_project_grading_details 
  
  
  
  match 'pick_subject_for_student_registrations' => "subject_registrations#pick_subject_for_student_registrations", :as => :pick_subject_for_student_registrations
  
  match 'select_subject_for_course_registration' => "course_registrations#select_subject_for_course_registration", :as => :select_subject_for_course_registration
  match 'select_course_for_course_registration/subject/:subject_id' => "course_registrations#select_course_for_course_registration", :as => :select_course_for_course_registration
  
  match 'new_teacher'           => 'enrollments#new_teacher'  , :as => :new_teacher
  match 'new_student'           => 'enrollments#new_student'  , :as => :new_student
  
  
  match 'select_active_project_for_admin' => "projects#select_active_project_for_admin", :as => :select_active_project_for_admin
  match 'gallery_mode_active_project/teacher/:teacher_id/project/:project_id' => "pictures#gallery_mode_active_project" , :as => :gallery_mode_active_project
  match 'view_submission_rate/:project_id' => 'projects#view_submission_rate', :as => :view_submission_rate
  match 'select_subject_for_project' => "projects#select_subject_for_project", :as => :select_subject_for_project
  match 'select_course_for_project/subject/:subject_id' => "projects#select_course_for_project", :as => :select_course_for_project
  match 'close_project' => "projects#close_project", :as => :close_project, :method => :post 
  match 'recover_project' => "projects#recover_project", :as => :recover_project, :method => :post 
  match 'past_projects' => "projects#past_projects", :as => :past_projects
  
  match 'select_active_project_to_be_edited' => "projects#select_active_project_to_be_edited", :as => :select_active_project_to_be_edited
  
  match 'select_subject_for_group' => "groups#select_subject_for_group", :as => :select_subject_for_group
  match 'select_course_for_group/subject/:subject_id' => "groups#select_course_for_group", :as => :select_course_for_group
  match 'select_group_for_group_leader' => "groups#select_group_for_group_leader", :as => :select_group_for_group_leader
  match 'select_group_leader/group/:group_id' => "groups#select_group_leader", :as => :select_group_leader, :method => :post
  match 'execute_select_group_leader' => "groups#execute_select_group_leader", :as => :execute_select_group_leader, :method => :post
  
  
  match 'select_subject_for_group_membership' => "group_memberships#select_subject_for_group_membership", :as => :select_subject_for_group_membership
  match 'select_course_for_group_membership/subject/:subject_id' => "group_memberships#select_course_for_group_membership", :as => :select_course_for_group_membership
  match 'select_group/course/:course_id' => "group_memberships#select_group", :as => :select_group
  
  
  match 'project_submissions_display' => "project_submissions#project_submissions_display", :as => :project_submissions_display
  match 'select_project_for_grading' => "projects#select_project_for_grading", :as => :select_project_for_grading
  match 'select_project_submission_for_grading/project/:project_id' => "project_submissions#select_project_submission_for_grading", :as => :select_project_submission_for_grading
  match 'show_submission_pictures_for_grading/project_submission/:project_submission_id' => "project_submissions#show_submission_pictures_for_grading", :as => :show_submission_pictures_for_grading
  match 'grade_project_submission_picture/picture/:picture_id' => "pictures#grade_project_submission_picture", :as => :grade_project_submission_picture
  match 'execute_grading/picture/:picture_id' => "pictures#execute_grading", :as => :execute_grading, :method => :post
  
  match 'gallery_mode_grading/project/:project_id' => "pictures#gallery_mode_grading" , :as => :gallery_mode_grading
  match 'gallery_picture_grading/project/:project_id/picture/:picture_id' => "pictures#gallery_picture_grading" , :as => :gallery_picture_grading
  match 'execute_grading_score/picture/:picture_id' => "pictures#execute_grading_score", :as => :execute_grading_score, :method => :post
  
  
  match 'select_project_to_publish_grade' => "projects#select_project_to_publish_grade", :as => :select_project_to_publish_grade
  match 'execute_publish_grade' => "projects#execute_publish_grade", :as => :execute_publish_grade, :method => :post 
=begin
  FOR STUDENTS 
=end  
  match 'student_projects' => "projects#student_projects", :as => :student_projects
  
  match 'project_submissions/:project_submission_id/create_revision/:original_pic_id' => "pictures#create_revision", :as => :create_revision
  
  resources :pictures do 
    resources :positional_comments
    resources :comments
  end
  
  match 'first_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_first_child_comment", :as => :create_first_child_comment
  match 'create_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_child_comment", :as => :create_child_comment
  match 'delete_original_image' => "pictures#delete_original_image", :as => :delete_original_image , :method => :post
  match 'delete_image_from_show' => "pictures#delete_image_from_show", :as => :delete_image_from_show , :method => :post
  
  
  
  
  
  match 'timezone_setup' => 'schools#timezone_setup', :as => :timezone_setup 
  match 'execute_timezone_setup' => 'schools#execute_timezone_setup', :as => :execute_timezone_setup, :method => :post 
  
  
  match 'delivery_method_setup' => 'schools#delivery_method_setup', :as => :delivery_method_setup 
  match 'execute_delivery_method_setup' => 'schools#execute_delivery_method_setup', :as => :execute_delivery_method_setup, :method => :post
  
  
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
  
  

end

app/models/group.rb
class Group < ActiveRecord::Base
  belongs_to :course
  
  has_many :users, :through => :group_memberships
  has_many :group_memberships
  
  def add_member( user ) 
    GroupMembership.create :user_id => user.id, :group_id => self.id 
  end
  
  
  def students
    self.users 
  end
  
  
  def has_student( student )
    not GroupMembership.find(:first, :conditions => {
      :user_id => student.id,
      :group_id => group.id 
    }).nil?
  end
  
  def group_leader
    if self.group_leader_id.nil?
      return nil
    end
      
    User.find_by_id( self.group_leader_id)
  end
  
  def is_leader?(user)
    self.group_leader_id == user.id 
  end
        
        
  def add_group_leader(user)
    self.group_leader_id = user.id
    self.save
  end
  
  def remove_group_leader(user)
    if self.group_leader_id == user.id
      self.group_leader_id = nil
      self.save
    end
  end
  
  def update_leader(user_id, decision) 
    if decision == TRUE_CHECK
      # ticking the checkbox 
      self.group_leader_id = user_id 
      self.save 
    elsif decision == FALSE_CHECK
      self.group_leader_id = nil 
      self.save
    end
    
    return self.group_leader 
  
  end
  
  
        
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def select_subject_for_group
    add_breadcrumb "Select Subject", "select_subject_for_group_url"
    @teacher = current_user
    @subjects = @teacher.all_subjects_taught
  end
  
  def select_course_for_group
    #current user is a teacher
    @subject = Subject.find_by_id( params[:subject_id])
    @courses = current_user.all_courses_for_subject( @subject )
    
    add_breadcrumb "Select Subject", "select_subject_for_project_url"
    set_breadcrumb_for @subject, 'select_course_for_group_path' + "(#{@subject.id})", 
                "Select Course for #{@subject.name}"
  end
  
  def new
    
    if not current_user.has_role?(:teacher)
      redirect_to root_url
      return
    end
    
    @course = Course.find_by_id( params[:course_id])
    
    if not current_user.teach_course?(@course)
      redirect_to root_url 
      return
    end
    
    
    @subject = @course.subject
    @groups =  @course.groups
    @new_group = Group.new


    add_breadcrumb "Select Subject", "select_subject_for_project_url"
    set_breadcrumb_for @subject, 'select_course_for_group_path' + "(#{@subject.id})", 
    "Select Course for #{@subject.name}"
    set_breadcrumb_for @course, 'new_course_group_path' + "(#{@course.id})", 
    "Create Group"


  end
  
  def create
    if not current_user.has_role?(:teacher)
      redirect_to root_url
      return
    end
    
    @course = Course.find_by_id( params[:course_id])
    
    if not current_user.teach_course?(@course)
      redirect_to root_url 
      return 
    end
    
    @group = Group.new(params[:group])
    @group.course_id = @course.id
    
    @group.save
    
    redirect_to new_course_group_url(@course)
  end
  
 

  def select_group_for_group_leader
    #current user is teacher
    add_breadcrumb "Select Group", "select_group_for_group_leader_url"
    
    # @courses = current_user.all_courses_taught
    @courses = current_user.all_courses_and_groups_taught
    
  end
  
  
  
  def select_group_leader
    
    if not current_user.has_role?(:teacher)
      redirect_to root_url
      return
    end
    
    @group = Group.find_by_id( params[:group_id])
    @course  = @group.course 
    
    if not current_user.teach_course?(@course)
      redirect_to root_url 
      return
    end
    
    
    @students = @group.students
    
    add_breadcrumb "Select Group", "select_group_for_group_leader_url"
    set_breadcrumb_for @group, 'select_group_leader_path' + "(#{@group.id})", 
                "Select Group Leader:  #{@group.name}"
  end
  
  
  def execute_select_group_leader
   
    
    if not current_user.has_role?(:teacher)
      redirect_to root_url
      return
    end
    
    @group_id = params[:membership_provider]
    @group = Group.find_by_id(@group_id)
    @course = @group.course 
    
    if not current_user.teach_course?(@course)
      redirect_to root_url 
      return
    end
    
    
    
    @user_id = params[:membership_consumer]
    @decision = params[:membership_decision].to_i
    
    
    group_leader = @group.update_leader(   @user_id, @decision )
        # 
        # if params[:action_to_the_student].to_i  == ADD_GROUP_LEADER
        #   @new_group_leader = User.find_by_id(  params[:user_id] )
        #   @old_group_leader = @group.group_leader 
        #   @group.add_group_leader( @new_group_leader ) 
        # elsif params[:action_to_the_student].to_i  == REMOVE_GROUP_LEADER
        #   @old_group_leader = User.find_by_id( params[:user_id] )
        #   @group.remove_group_leader( @old_group_leader )
        # end
    
    
    
    respond_to do |format|
      format.html {  redirect_to select_group_leader_path(@group) }
      format.js
    end
    
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/execute_select_group_leader.js.erb
$(document).ready(function(){
  location.reload();
});

app/views/groups/new.html.erb
<div class="span9 content">
  <%= create_guide("New Project", 
        "Create the projects details for subject: <b>#{@subject.name}</b>").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <div class="row-fluid">
    <div class="span8">


      <%= form_for @new_group  ,:url => course_groups_url(@course),
          :html => {:class => "form-horizontal"} do |f| %>
        <div class="control-group">
          <%= f.label :name, "Group Name" %>
          <div class="controls">
            <%= f.text_field :name, :class=>"input-xlarge" %>
            <!-- <p class="help-block">Masukkan kode kelas.</p> -->
          </div>
        </div>
        
        
        
        
        
        
        <div class="form-actions">
          <button class="btn btn-primary" type="submit">Create Group</button>
        </div>
      <% end %>
      
      
      

    </div><!--/span-->

    <div class="span4">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th>Total Groups: <%= @groups.count%></th></tr>
        </thead>
        <tbody>
          <% @groups.each do |group| %>
            <tr>
              <td><%= group.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div><!--/span-->
    
  </div><!--/row-->

</div><!--/span-->

app/views/groups/select_course_for_group.html.erb
<div class="span9 content">
  
  <%= create_guide("Select the Course", 
        "Select the course where some projects will be created.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  
  
  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Subject name</th>
            <th>Students</th>
            <th>Groups</th>
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
            <tr>
              <td><%= link_to "#{course.name}", new_course_group_url( course) %></td>
              <td><%=  course.students.count  %></td>
              <td><%= course.groups.count %></td>
            </tr>
          <% end %>


         
        </tbody>
      </table>
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->

      
      <!-- <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/groups/select_group_for_group_leader.html.erb
<div class="span9 content">
  
  <%= create_guide("Select the Group", 
        "Select the group to assign group leader ").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  

  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Group name</th>
            <th>Group Leader</th>
            <th>Course Name</th>
            <th>Subject Name</th>
            
          </tr>
        </thead>
        <tbody>
          <% @courses.each do |course| %>
            <% course.groups.each do |group| %>
            <tr>
              <td> <%= link_to "#{group.name}", select_group_leader_url(group) %></td>
              <% if group.group_leader == nil %>
                <td>no</td>
              <% else %>
                <td>yes</td>
              <% end %>
              <td><%=  group.course.name%></td>
              <td><%=  group.course.subject.name  %></td>
            </tr>
            <% end %>
          <% end %>


         
        </tbody>
      </table>
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->

      
      <!-- <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/groups/select_group_leader.html.erb
<div class="span9 content">
  
  <%= create_guide("Select the Group Leader", 
        "Pick one of the member to be the group leader").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  

  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Member Name</th>
            <th>Member NIM</th>
            <th>Select Group Leader</th>
            
          </tr>
        </thead>
        <tbody>
          <% @students.each do |student| %>
            <tr>
              <td><%= student.name %></td>

              <td> <%= student.nim %> </td>
              <td class="well">
                <label class="checkbox">
                  <% checkbox_value = @group.is_leader?(student)  %>
                  
                  <%= check_box_tag 'is_checked', get_checkbox_value(checkbox_value )   , 
                      checkbox_value, :class => 'checkbox_tracker single-submit', 
                      :id => "provider_#{@group.id}-consumer_#{student.id}" %> Taking
                </label>

              </td>
            </tr>
          <% end %>


         
        </tbody>
      </table>
      
      
        <div class=" hidden" id="checkbox_form_wrapper">
          <%= form_tag  execute_select_group_leader_url , :method => :post  do  %>
            <%= hidden_field_tag 'membership_provider' , ''  %>
            <%= hidden_field_tag 'membership_consumer', '' %>
            <%= hidden_field_tag 'membership_decision', '' %>
          <% end %>
        </div>
     
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/groups/select_subject_for_group.html.erb
<div class="span9 content">
  
  <%= create_guide("Select the Subject", 
        "Select the subject where a group will be created ").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  

  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Subject name</th>
            <th>Description</th>
            <th>Students</th>
          </tr>
        </thead>
        <tbody>
          <% @subjects.each do |subject| %>
            <tr>
              <td><%= link_to "#{subject.name}", select_course_for_group_url(subject) %></td>
              <td><%=  subject.description %></td>
              <td><%=  subject.students_count  %></td>
            </tr>
          <% end %>


         
        </tbody>
      </table>
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->

      
      <!-- <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>