config/routes.rb
Debita46::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users 
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  root :to => 'home#dashboard'
  
  match 'raise_exception' => 'home#raise_exception', :as => :raise_exception 
  
  resources :terms   
  resources :enrollments
  resources :subjects do
    resources :courses 
    resources :subject_teaching_assignments
    resources :subject_registrations 
  end
  
  resources :courses do 
    resources :course_teaching_assignments
    resources :course_registrations
    resources :projects
    resources :groups
  end
  
  resources :projects
  resources :project_submissions
  resources :project_submissions do 
    resources :pictures
  end
  resources :user do 
    resources :project_submissions
  end
  
  resources :groups do 
    resources :group_memberships
  end
  resources :group_memberships
  
=begin
  CREATE SUBJECT, TERM_based
=end

  match 'select_term_to_create_subject' => 'terms#select_term_to_create_subject', :as => :select_term_to_create_subject
  match 'execute_close_term' => 'terms#execute_close_term', :as => :execute_close_term, :method => :post 
  match 'closed_terms' => 'terms#closed_terms', :as => :closed_terms
  
  
  match 'active_subjects_management' => "subjects#active_subjects_management", :as => :active_subjects_management
  match 'passive_subjects_management' => "subjects#passive_subjects_management", :as => :passive_subjects_management
  match 'duplicate_active_subject/:subject_id' => "subjects#duplicate_active_subject" , :as => :duplicate_active_subject
  match 'duplicate_passive_subject/:subject_id' => "subjects#duplicate_passive_subject" , :as => :duplicate_passive_subject
  
  match 'execute_duplicate_subject' => "subjects#execute_duplicate_subject" , :as => :execute_duplicate_subject, :method => :post 
  match 'close_subject' => "subjects#close_subject", :as => :close_subject, :method => :post 
  match 'recover_subject' => "subjects#recover_subject", :as => :recover_subject, :method => :post 
  
  match 'new_subject_teaching_assignment' => "subjects#new_subject_teaching_assignment", :as => :new_subject_teaching_assignment
  match 'pick_subject_for_course_teaching_assignment' => "courses#pick_subject_for_course_teaching_assignment", :as => :pick_subject_for_course_teaching_assignment
  match 'new_course_teaching_assignment/:subject_id' => "courses#new_course_teaching_assignment", :as => :new_course_teaching_assignment
  
  match 'select_course_for_grade_summary' => "courses#select_course_for_grade_summary", :as => :select_course_for_grade_summary 
  match 'show_student_grades_for_course/:course_id' => "courses#show_student_grades_for_course", :as => :show_student_grades_for_course 
  match 'show_project_grading_details/project/:project_id/student/:student_id' => "courses#show_project_grading_details", :as => :show_project_grading_details 
  
  
  
  match 'pick_subject_for_student_registrations' => "subject_registrations#pick_subject_for_student_registrations", :as => :pick_subject_for_student_registrations
  
  match 'select_subject_for_course_registration' => "course_registrations#select_subject_for_course_registration", :as => :select_subject_for_course_registration
  match 'select_course_for_course_registration/subject/:subject_id' => "course_registrations#select_course_for_course_registration", :as => :select_course_for_course_registration
  
  match 'new_teacher'           => 'enrollments#new_teacher'  , :as => :new_teacher
  match 'new_student'           => 'enrollments#new_student'  , :as => :new_student
  
  
  match 'select_active_project_for_admin' => "projects#select_active_project_for_admin", :as => :select_active_project_for_admin
  match 'gallery_mode_active_project/teacher/:teacher_id/project/:project_id' => "pictures#gallery_mode_active_project" , :as => :gallery_mode_active_project
  match 'view_submission_rate/:project_id' => 'projects#view_submission_rate', :as => :view_submission_rate
  match 'select_subject_for_project' => "projects#select_subject_for_project", :as => :select_subject_for_project
  match 'select_course_for_project/subject/:subject_id' => "projects#select_course_for_project", :as => :select_course_for_project
  match 'close_project' => "projects#close_project", :as => :close_project, :method => :post 
  match 'recover_project' => "projects#recover_project", :as => :recover_project, :method => :post 
  match 'past_projects' => "projects#past_projects", :as => :past_projects
  
  match 'select_active_project_to_be_edited' => "projects#select_active_project_to_be_edited", :as => :select_active_project_to_be_edited
  
  match 'select_subject_for_group' => "groups#select_subject_for_group", :as => :select_subject_for_group
  match 'select_course_for_group/subject/:subject_id' => "groups#select_course_for_group", :as => :select_course_for_group
  match 'select_group_for_group_leader' => "groups#select_group_for_group_leader", :as => :select_group_for_group_leader
  match 'select_group_leader/group/:group_id' => "groups#select_group_leader", :as => :select_group_leader, :method => :post
  match 'execute_select_group_leader' => "groups#execute_select_group_leader", :as => :execute_select_group_leader, :method => :post
  
  
  match 'select_subject_for_group_membership' => "group_memberships#select_subject_for_group_membership", :as => :select_subject_for_group_membership
  match 'select_course_for_group_membership/subject/:subject_id' => "group_memberships#select_course_for_group_membership", :as => :select_course_for_group_membership
  match 'select_group/course/:course_id' => "group_memberships#select_group", :as => :select_group
  
  
  match 'project_submissions_display' => "project_submissions#project_submissions_display", :as => :project_submissions_display
  match 'select_project_for_grading' => "projects#select_project_for_grading", :as => :select_project_for_grading
  match 'select_project_submission_for_grading/project/:project_id' => "project_submissions#select_project_submission_for_grading", :as => :select_project_submission_for_grading
  match 'show_submission_pictures_for_grading/project_submission/:project_submission_id' => "project_submissions#show_submission_pictures_for_grading", :as => :show_submission_pictures_for_grading
  match 'grade_project_submission_picture/picture/:picture_id' => "pictures#grade_project_submission_picture", :as => :grade_project_submission_picture
  match 'execute_grading/picture/:picture_id' => "pictures#execute_grading", :as => :execute_grading, :method => :post
  
  match 'gallery_mode_grading/project/:project_id' => "pictures#gallery_mode_grading" , :as => :gallery_mode_grading
  match 'gallery_picture_grading/project/:project_id/picture/:picture_id' => "pictures#gallery_picture_grading" , :as => :gallery_picture_grading
  match 'execute_grading_score/picture/:picture_id' => "pictures#execute_grading_score", :as => :execute_grading_score, :method => :post
  
  
  match 'select_project_to_publish_grade' => "projects#select_project_to_publish_grade", :as => :select_project_to_publish_grade
  match 'execute_publish_grade' => "projects#execute_publish_grade", :as => :execute_publish_grade, :method => :post 
=begin
  FOR STUDENTS 
=end  
  match 'student_projects' => "projects#student_projects", :as => :student_projects
  
  match 'project_submissions/:project_submission_id/create_revision/:original_pic_id' => "pictures#create_revision", :as => :create_revision
  
  resources :pictures do 
    resources :positional_comments
    resources :comments
  end
  
  match 'first_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_first_child_comment", :as => :create_first_child_comment
  match 'create_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_child_comment", :as => :create_child_comment
  match 'delete_original_image' => "pictures#delete_original_image", :as => :delete_original_image , :method => :post
  match 'delete_image_from_show' => "pictures#delete_image_from_show", :as => :delete_image_from_show , :method => :post
  
  
  
  
  
  match 'timezone_setup' => 'schools#timezone_setup', :as => :timezone_setup 
  match 'execute_timezone_setup' => 'schools#execute_timezone_setup', :as => :execute_timezone_setup, :method => :post 
  
  
  match 'delivery_method_setup' => 'schools#delivery_method_setup', :as => :delivery_method_setup 
  match 'execute_delivery_method_setup' => 'schools#execute_delivery_method_setup', :as => :execute_delivery_method_setup, :method => :post
  
  
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
  
  

end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :course 

  
  # student project submission
  has_many :users, :through => :project_submissions
  has_many :project_submissions
  
  belongs_to :term 
  after_create :hook_to_term 
  
  def hook_to_term
    self.term_id = self.course.term_id 
    self.save 
  end
  
  
  def Project.create_project_by_project_creator( project_creator , new_project)
    if new_project.save 
      # add_create_project_to_user_activity(EVENT_TYPE[:create_project]project_creator)
      
      if new_project.course 
        puts "The course is #{new_project.course.name}\n"*10
      else
        puts "The course is empty\n"*5
      end
      
      UserActivity.create_new_entry(EVENT_TYPE[:create_project], 
                        project_creator, 
                        new_project , 
                        new_project.course )
                        
      puts "Done with creating new user_activity in project"
                        
      return new_project
    else
      return nil
    end
  end
  
  def create_project_submissions
    students = self.course.students
    students.each do |student|
      ProjectSubmission.create :user_id => student.id, :project_id => self.id
    end
  end
  
  
  def format_deadline_date
    datetime = self.deadline_datetime
    "#{datetime.month}/#{datetime.day}/#{datetime.year}"
  end
  
  def passed_deadline?
    Time.now.to_datetime > self.deadline_datetime
  end
  
  def submission_has_exceed_quota(student)
    project_submission  = ProjectSubmission.find(:first, :conditions => {
      :user_id => student.id,
      :project_id => self.id 
    })
    
    project_submission.exceed_quota?
  end
  
  def is_closed?
    self.is_active == false 
  end
  
  def in_between_starting_and_deadline_time?
    current_time = Time.now.to_datetime
    deadline_time = ''
    starting_time = ''
    
    if self.deadline_datetime.nil?
      deadline_time = current_time 
    else
      deadline_time = self.deadline_datetime
    end
    
    if self.starting_datetime.nil?
      starting_time = current_time 
    else
      starting_time = self.starting_datetime
    end
    
    (current_time <=  deadline_time) && (current_time >= starting_time )
  end
  
  def earlier_than_starting_time?(current_time )
    current_time < starting_datetime
  end
  
  def later_than_deadline_time?(current_time )
    current_time > deadline_datetime
  end
  
  def possible_to_upload_more?(student)
    # 1. time <= deadline_datetime
    # 2. hasn't exceeded quota
    # 3. project is not closed 
    
    ( self.in_between_starting_and_deadline_time? ) and 
    (not self.submission_has_exceed_quota(student) ) and 
    (not  self.is_closed?)
    
  end
  
  def allow_student_activities?
    ( self.in_between_starting_and_deadline_time? ) and 
    (not self.is_closed?)
  end
  
  
  
  
  
  def group_project?
    self.is_group_project
  end
  
  def deactivate
    self.is_active = false
    self.save
  end
  
  def re_activate
    self.is_active = true
    self.save
  end
  
 
  
  def created_by?(current_user)
    if not current_user.has_role?(:teacher)
      return false 
    end
    
    not current_user.all_projects.where(:project_id => self.id ).nil?
  end

=begin
  Time display logic
=end
  def get_starting_datetime_local_time
    school = self.course.subject.school 
    self.starting_datetime.in_time_zone(school.get_time_zone)
  end
  
  def get_deadline_datetime_local_time
    school = self.course.subject.school 
    self.deadline_datetime.in_time_zone(school.get_time_zone)
  end

  def starting_hour
    if self.starting_datetime.nil?
      return 0
    end
    
    self.get_starting_datetime_local_time.hour
  end
  
  def starting_minute
    if self.starting_datetime.nil?
      return 0
    end
    
    self.get_starting_datetime_local_time.min
  end
  
  def deadline_hour
    if self.starting_datetime.nil?
      return 0
    end
    
    self.get_deadline_datetime_local_time.hour
  end
  
  def deadline_minute
    if self.starting_datetime.nil?
      return 0
    end
    
    self.get_deadline_datetime_local_time.min
  end
  
=begin
  Completion logic 
=end
  def completion_rate
    project_submission_limit = self.total_submission
    completed_submissions = self.project_submissions.
                      where(:total_original_submission => project_submission_limit ).
                      count 
  end
  
 
=begin
  grade code 
=end

  def total_graded_submissions
    #  we want to find those submissions where the score is not nil
    self.project_submissions.
          where{
            ( score.not_eq nil ) | 
            ( score.not_eq 0 )
          }.count 
  end
  
# ps = ProjectSubmission.find(:first, :conditions => {:user_id => student.id, :project_id => uts.id } ) 
  
  def total_completed_submissions
    self.project_submissions.where{
      total_original_submission.gt 0 
    }.count
  end
  
  def get_grade_for( student )
    project_submission = self.project_submissions.find(:first, :conditions => {
      :project_id => self.id,
      :user_id => student.id 
    })
   
    # graded_pictures_count = project_submission.pictures.where(:is_deleted=> false, :is_graded => true).count
    # if graded_pictures_count == 0 
    #   return nil
    # else
    #   return project_submission.pictures.
    #           where(:is_deleted=> false, :is_graded => true).
    #           maximum("score")
    # end
    project_submission.score 
  end
  
  def activate_publish_grade
    self.publish_grade = true 
    self.save 
  end
  
=begin
  DATA PLOTTING AND ANALYSIS
=end

  def active_days
    starting_date = self.starting_datetime.to_date 
    ending_date  = self.deadline_datetime.to_date
    (ending_date-starting_date).to_i
  end
  
  def day_and_total_submission_pairs
    project_submission_id_list = self.project_submissions.map {|x| x.id }
    
    active_days = self.active_days
    result_hash = {}
    (0..active_days).each do |day_count|
      start_datetime = self.starting_datetime + day_count.day
      end_datetime  = self.starting_datetime + (day_count + 1  ).day - 1.second
      # Client.where(:created_at => (params[:start_date].to_date)..(params[:end_date].to_date))
      submitted_picture_count = Picture.find(:all, :conditions => {
        :project_submission_id => project_submission_id_list,
        :created_at => (start_datetime..end_datetime)
      }).count
      
      result_hash[day_count] = submitted_picture_count
    end
    return result_hash
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/close_project.js.erb
$(document).ready(function(){
  $("#entry_<%= @project.id %>").hideLoading();
  $("#entry_row_<%= @project.id %>").remove();
});

app/views/projects/edit.html.erb
<div class="span9 content">
  <%= create_guide("New Project", 
        "Create the projects details for subject: <b>#{@subject.name}</b>, course: <b>#{@course.name}</b>").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <div class="row-fluid">
    <div class="span8">


      <%= form_for @project  ,:url => project_url(@project), :html => {:class => "form-horizontal"} do |f| %>
        <div class="control-group">
          <%= f.label :title, "Project Title" %>
          <div class="controls">
            <%= f.text_field :title, :class=>"input-xlarge" %>
            <!-- <p class="help-block">Masukkan kode kelas.</p> -->
          </div>
        </div>
        
        <div class="control-group">
          <%= f.label :description, "Project Description" %>
          <div class="controls">
            <%= f.text_area :description, :class=>"input-xlarge", :rows => 5 %>
            <!-- <p class="help-block">Masukkan kode kelas.</p> -->
          </div>
        </div>
        
        
        <div class="control-group">
          <%= f.label :total_submission, "Total Submission" %>
          <div class="controls">
            <%= f.text_field :total_submission, :class=>"input-xlarge" %>
            <p class="help-block">Jumlah hasil yang harus dikumpulkan? <br />Isi dengan angka, contoh: <b>5</b> (untuk memberi quota upload 5 gambar)</p>
          </div>
        </div>
        
        
        
        <!-- <div class="control-group">
              <%#= f.label :deadline_date, "Deadline" %>
              <div class="controls">
                <%#= f.text_field :deadline_datetime, :class=>"input-xlarge"  ,'data-datepicker'=>'datepicker',
                      :value => @project.format_deadline_date %>
                <p class="help-block">Langsung saja dipilih. Tidak usah di ketik jam nya. By default, 
                    project akan berakhir pada <strong>tengah malam</strong>.</p>
              </div>
            </div>
             -->
        
        
        
        <div class="control-group">
          <%= f.label :starting_datetime, "Starting Date" %>
          <div class="controls">
            <%= f.text_field :starting_datetime, :class=>"input-xlarge"  ,
                  'data-datepicker'=>'datepicker',
                  :value =>format_date_from_datetime(@project.starting_datetime)   %>
            <p class="help-block"></p>
          </div>
        </div>
        
        
        <div class="control-group">
          <%= label_tag :starting_hour, "Starting Hour" %>
          <div class="controls">
            <%= select_tag "starting_hour", 
              select_hour_options_with_selected( @project.starting_hour ).html_safe %>
            <p class="help-block"></p>
          </div>
        </div>
        
        <div class="control-group">
          <%= label_tag :starting_minute, "Starting Minute" %>
          <div class="controls">
            <%= select_tag "starting_minute", 
              select_minute_options_with_selected( @project.starting_minute ).html_safe %>
            <p class="help-block"></p>
          </div>
        </div>
        
        <hr />
        
        
        <div class="control-group">
          <%= f.label :deadline_datetime, "Deadline Date" %>
          <div class="controls">
            <%= f.text_field :deadline_datetime, 
              :class=>"input-xlarge"  ,'data-datepicker'=>'datepicker',
              :value =>format_date_from_datetime(@project.deadline_datetime)  %>
              <!-- move this value to @project.get_deadline_datetime_local_time -->
            <p class="help-block"></p>
          </div>
        </div>
        
        
        <div class="control-group">
          <%= label_tag :deadline_hour, "Deadline Hour" %>
          <div class="controls">
            <%= select_tag "deadline_hour", 
              select_hour_options_with_selected( @project.deadline_hour ).html_safe %>
            <p class="help-block"></p>
          </div>
        </div>
        
        <div class="control-group">
          <%= label_tag :deadline_minute, "Deadline Minute" %>
          <div class="controls">
            <%= select_tag "deadline_minute", 
              select_minute_options_with_selected( @project.deadline_minute ).html_safe %>
            <p class="help-block"></p>
          </div>
        </div>
        
        
        
        <!-- <div class="control-group">
             <label class="control-label">Group Project?</label>
             <div class="controls">
               <label class="radio">
                 <%= f.radio_button "is_group_project", TRUE_CHECK %> Yes
               
               </label>
               <label class="radio">
                 <%= f.radio_button "is_group_project", FALSE_CHECK %> No
     
               </label>
             </div>
           </div> -->
        
        
        
        
        <div class="form-actions">
          <button class="btn btn-primary" type="submit">Update Project</button>
        </div>
      <% end %>
      
      
      

    </div><!--/span-->

    <div class="span4">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th>Total Projects: <%= @projects.count%></th></tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr>
              <td><%= project.title %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div><!--/span-->
    
  </div><!--/row-->

</div><!--/span-->

app/views/projects/past_projects.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Past Projects", 
        "Collection of all past projects in the current academic year.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
 
  
  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Title</th>
            <th>Course</th>
            <th>Subject</th>
            <th>Deadline</th>
            <th>Close</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr id="entry_row_<%= project.id %>">
             
              <td><%= link_to "#{project.title}", select_project_submission_for_grading_path(project) %></td>
              <td><%= project.course.name %>
              <td><%= project.course.subject.code %>
              <td><%= project.deadline_datetime.in_time_zone("Jakarta") %>
              
              <td>
                <%= link_to "Recover", '#', 
                          :class => "btn btn-danger entry-link entry-recover",
                          :id => "entry_#{project.id}" %>
              </td>
              
                
            </tr>
          <% end %>


         
        </tbody>
      </table>
      
      
        <div class=" hidden" id="close-entry">
          <%= form_tag  recover_project_url  , :method => :post  do  %>
            <%= hidden_field_tag 'entry_id' , ''  %>
          <% end %>
        </div>
        
        
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->
   
      
<!--       <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/projects/select_active_project_for_admin.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Grade Project", 
        "Select the project to be graded.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <h3>Total Teachers: 3</h3>
  <hr />
  
  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Title</th>
            <th>Course</th>
            <th>Subject</th>
            <th>Deadline</th>
            <th>Total Student</th>
            <th>Completed Submission</th>
            <th>Close</th>
            <th>Graph</th>
          </tr>
        </thead>
        <tbody>
          
          <% @teachers.each do |teacher| %>
            <% teacher.all_active_projects.each do |project| %>
              <tr id="entry_row_<%= project.id %>">
             
                <td><%= link_to "#{project.title}", gallery_mode_active_project_url(teacher, project) %></td>
                <td><%= project.course.name %>
                <td><%= project.course.subject.code %>
                <td><%= project.deadline_datetime.in_time_zone("Jakarta") %>
              
                <td><%= project.project_submissions.count %></td>
                <td><%= project.completion_rate %></td>
                <td>
                  <%= link_to "Close", '#', 
                            :class => "btn btn-danger entry-link entry-closer",
                            :id => "entry_#{project.id}" %>
                </td>
                
                <td>
                  <%= link_to "Graph", view_submission_rate_url(project), 
                            :class => "btn",
                            :id => "graph_entry_#{project.id}" %>
                </td>
              
                
              </tr>
            <% end %>
            
          <% end %>
        </tbody>
      </table>
      
      
        <div class=" hidden" id="close-entry">
          <%= form_tag  close_project_url  , :method => :post  do  %>
            <%= hidden_field_tag 'entry_id' , ''  %>
          <% end %>
        </div>
        
        
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->
   
      
<!--       <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/projects/select_active_project_to_be_edited.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Grade Project", 
        "Select the project to be graded.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <h3>Total Teachers: 3</h3>
  <hr />
  
  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Title</th>
            <th>Course</th>
            <th>Subject</th>
            <th>Deadline</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr id="entry_row_<%= project.id %>">
             
              <td><%= link_to "#{project.title}", edit_project_url(project) %></td>
              <td><%= project.course.name %>
              <td><%= project.course.subject.code %>
              <td><%= project.deadline_datetime.in_time_zone("Jakarta") %>
            </tr>
          <% end %>


         
        </tbody>
      </table>
      
      
        <div class=" hidden" id="close-entry">
          <%= form_tag  close_project_url  , :method => :post  do  %>
            <%= hidden_field_tag 'entry_id' , ''  %>
          <% end %>
        </div>
        
        
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->
   
      
<!--       <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/projects/select_project_for_grading.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Grade Project", 
        "Select the project to be graded.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  <h3>Total Teachers: 3</h3>
  <hr />
  
  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Title</th>
            <th>Course</th>
            <th>Subject</th>
            <th>Deadline</th>
            <th>Total Student</th>
            <th>Completed Submission</th>
            <th>Close</th>
          </tr>
        </thead>
        <tbody>
          <% @projects.each do |project| %>
            <tr id="entry_row_<%= project.id %>">
             
              <td><%= link_to "#{project.title}", select_project_submission_for_grading_path(project) %></td>
              <td><%= project.course.name %>
              <td><%= project.course.subject.name %>
              <td><%= project.deadline_datetime.in_time_zone("Jakarta") %>
              
              <td><%= project.project_submissions.count %></td>
              <td><%= project.completion_rate %></td>
              <td>
                <%= link_to "Close", '#', 
                          :class => "btn btn-danger entry-link entry-closer",
                          :id => "entry_#{project.id}" %>
              </td>
              
                
            </tr>
          <% end %>


         
        </tbody>
      </table>
      
      
        <div class=" hidden" id="close-entry">
          <%= form_tag  close_project_url  , :method => :post  do  %>
            <%= hidden_field_tag 'entry_id' , ''  %>
          <% end %>
        </div>
        
        
      
      <!-- <div class="alert alert-success allert-message">
           <a class="close" href="#">&times;</a>
           <strong>Well done!</strong> You successfully read this important alert message.
         </div> -->
   
      
<!--       <div class="form-actions">
        <%#= hidden_field_tag 'destination_url', 
                subject_subject_teaching_assignments_url(@subject) ,
                 :id => "destination_url" %>

        <button class="btn btn-large btn-primary"
              type="submit" id="save_button">Save changes</button>
      </div> -->


      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>