config/routes.rb
Debita46::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users 
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  root :to => 'home#dashboard'
  
  match 'raise_exception' => 'home#raise_exception', :as => :raise_exception 
  
  resources :terms   
  resources :enrollments
  resources :subjects do
    resources :courses 
    resources :subject_teaching_assignments
    resources :subject_registrations 
  end
  
  resources :courses do 
    resources :course_teaching_assignments
    resources :course_registrations
    resources :projects
    resources :groups
  end
  
  resources :projects
  resources :project_submissions
  resources :project_submissions do 
    resources :pictures
  end
  resources :user do 
    resources :project_submissions
  end
  
  resources :groups do 
    resources :group_memberships
  end
  resources :group_memberships
  
=begin
  CREATE SUBJECT, TERM_based
=end

  match 'select_term_to_create_subject' => 'terms#select_term_to_create_subject', :as => :select_term_to_create_subject
  match 'execute_close_term' => 'terms#execute_close_term', :as => :execute_close_term, :method => :post 
  match 'closed_terms' => 'terms#closed_terms', :as => :closed_terms
  
  
  match 'active_subjects_management' => "subjects#active_subjects_management", :as => :active_subjects_management
  match 'passive_subjects_management' => "subjects#passive_subjects_management", :as => :passive_subjects_management
  match 'duplicate_active_subject/:subject_id' => "subjects#duplicate_active_subject" , :as => :duplicate_active_subject
  match 'duplicate_passive_subject/:subject_id' => "subjects#duplicate_passive_subject" , :as => :duplicate_passive_subject
  
  match 'execute_duplicate_subject' => "subjects#execute_duplicate_subject" , :as => :execute_duplicate_subject, :method => :post 
  match 'close_subject' => "subjects#close_subject", :as => :close_subject, :method => :post 
  match 'recover_subject' => "subjects#recover_subject", :as => :recover_subject, :method => :post 
  
  match 'new_subject_teaching_assignment' => "subjects#new_subject_teaching_assignment", :as => :new_subject_teaching_assignment
  match 'pick_subject_for_course_teaching_assignment' => "courses#pick_subject_for_course_teaching_assignment", :as => :pick_subject_for_course_teaching_assignment
  match 'new_course_teaching_assignment/:subject_id' => "courses#new_course_teaching_assignment", :as => :new_course_teaching_assignment
  
  match 'select_course_for_grade_summary' => "courses#select_course_for_grade_summary", :as => :select_course_for_grade_summary 
  match 'show_student_grades_for_course/:course_id' => "courses#show_student_grades_for_course", :as => :show_student_grades_for_course 
  match 'show_project_grading_details/project/:project_id/student/:student_id' => "courses#show_project_grading_details", :as => :show_project_grading_details 
  
  
  
  match 'pick_subject_for_student_registrations' => "subject_registrations#pick_subject_for_student_registrations", :as => :pick_subject_for_student_registrations
  
  match 'select_subject_for_course_registration' => "course_registrations#select_subject_for_course_registration", :as => :select_subject_for_course_registration
  match 'select_course_for_course_registration/subject/:subject_id' => "course_registrations#select_course_for_course_registration", :as => :select_course_for_course_registration
  
  match 'new_teacher'           => 'enrollments#new_teacher'  , :as => :new_teacher
  match 'new_student'           => 'enrollments#new_student'  , :as => :new_student
  
  
  match 'select_active_project_for_admin' => "projects#select_active_project_for_admin", :as => :select_active_project_for_admin
  match 'gallery_mode_active_project/teacher/:teacher_id/project/:project_id' => "pictures#gallery_mode_active_project" , :as => :gallery_mode_active_project
  match 'view_submission_rate/:project_id' => 'projects#view_submission_rate', :as => :view_submission_rate
  match 'select_subject_for_project' => "projects#select_subject_for_project", :as => :select_subject_for_project
  match 'select_course_for_project/subject/:subject_id' => "projects#select_course_for_project", :as => :select_course_for_project
  match 'close_project' => "projects#close_project", :as => :close_project, :method => :post 
  match 'recover_project' => "projects#recover_project", :as => :recover_project, :method => :post 
  match 'past_projects' => "projects#past_projects", :as => :past_projects
  
  match 'select_active_project_to_be_edited' => "projects#select_active_project_to_be_edited", :as => :select_active_project_to_be_edited
  
  match 'select_subject_for_group' => "groups#select_subject_for_group", :as => :select_subject_for_group
  match 'select_course_for_group/subject/:subject_id' => "groups#select_course_for_group", :as => :select_course_for_group
  match 'select_group_for_group_leader' => "groups#select_group_for_group_leader", :as => :select_group_for_group_leader
  match 'select_group_leader/group/:group_id' => "groups#select_group_leader", :as => :select_group_leader, :method => :post
  match 'execute_select_group_leader' => "groups#execute_select_group_leader", :as => :execute_select_group_leader, :method => :post
  
  
  match 'select_subject_for_group_membership' => "group_memberships#select_subject_for_group_membership", :as => :select_subject_for_group_membership
  match 'select_course_for_group_membership/subject/:subject_id' => "group_memberships#select_course_for_group_membership", :as => :select_course_for_group_membership
  match 'select_group/course/:course_id' => "group_memberships#select_group", :as => :select_group
  
  
  match 'project_submissions_display' => "project_submissions#project_submissions_display", :as => :project_submissions_display
  match 'select_project_for_grading' => "projects#select_project_for_grading", :as => :select_project_for_grading
  match 'select_project_submission_for_grading/project/:project_id' => "project_submissions#select_project_submission_for_grading", :as => :select_project_submission_for_grading
  match 'show_submission_pictures_for_grading/project_submission/:project_submission_id' => "project_submissions#show_submission_pictures_for_grading", :as => :show_submission_pictures_for_grading
  match 'grade_project_submission_picture/picture/:picture_id' => "pictures#grade_project_submission_picture", :as => :grade_project_submission_picture
  match 'execute_grading/picture/:picture_id' => "pictures#execute_grading", :as => :execute_grading, :method => :post
  
  match 'gallery_mode_grading/project/:project_id' => "pictures#gallery_mode_grading" , :as => :gallery_mode_grading
  match 'gallery_picture_grading/project/:project_id/picture/:picture_id' => "pictures#gallery_picture_grading" , :as => :gallery_picture_grading
  match 'execute_grading_score/picture/:picture_id' => "pictures#execute_grading_score", :as => :execute_grading_score, :method => :post
  
  
  match 'select_project_to_publish_grade' => "projects#select_project_to_publish_grade", :as => :select_project_to_publish_grade
  match 'execute_publish_grade' => "projects#execute_publish_grade", :as => :execute_publish_grade, :method => :post 
=begin
  FOR STUDENTS 
=end  
  match 'student_projects' => "projects#student_projects", :as => :student_projects
  
  match 'project_submissions/:project_submission_id/create_revision/:original_pic_id' => "pictures#create_revision", :as => :create_revision
  
  resources :pictures do 
    resources :positional_comments
    resources :comments
  end
  
  match 'first_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_first_child_comment", :as => :create_first_child_comment
  match 'create_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_child_comment", :as => :create_child_comment
  match 'delete_original_image' => "pictures#delete_original_image", :as => :delete_original_image , :method => :post
  match 'delete_image_from_show' => "pictures#delete_image_from_show", :as => :delete_image_from_show , :method => :post
  
  
  
  
  
  match 'timezone_setup' => 'schools#timezone_setup', :as => :timezone_setup 
  match 'execute_timezone_setup' => 'schools#execute_timezone_setup', :as => :execute_timezone_setup, :method => :post 
  
  
  match 'delivery_method_setup' => 'schools#delivery_method_setup', :as => :delivery_method_setup 
  match 'execute_delivery_method_setup' => 'schools#execute_delivery_method_setup', :as => :execute_delivery_method_setup, :method => :post
  
  
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
  
  

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  belongs_to :school
  
  # teacher, assigned to teach the subject
  has_many :users, :through => :subject_teaching_assignments
  has_many :subject_teaching_assignments
  
  has_many :courses
  
  # student, registering for the subject
  has_many :users, :through => :subject_registrations
  has_many :subject_registrations
  
  belongs_to :term 
  
  
  def find_course_by_name( name ) 
    Course.find(:first, :conditions => {
      :name => name.upcase ,
      :subject_id => self.id
    })
  end
  
  def teachers
    # SubjectTeachingAssignment.find(:all, :conditions => {:subject_id => self.id})
    # 
    # self.users.joins(:assignments).where{
    #    (assignments.role_id == student_role.id )
    #  }
    #  
     subject = self 
     User.joins(:subject_teaching_assignments).where{
       (subject_teaching_assignments.subject_id == subject.id )
     }
  end
  
  def students
    self.subject_registrations
    User.where(:id => self.subject_registrations.map{|x| x.user_id }).order("nim DESC")
  end
  
  def students_count
    self.students.count
  end
  
=begin
Teacher code
=end

  def add_teacher(teacher)
    SubjectTeachingAssignment.create :user_id => teacher.id, :subject_id => self.id
  end
  
=begin
Student code
=end

  def add_student( student )
    SubjectRegistration.create :user_id => student.id, :subject_id => self.id
  end
  
  
  
=begin
  Subject school_admin: to close the subject
=end

  def close_subject
    # this is the best done with delayed job 
    # set is active to 
    # 1. Subject Registration
    # 2. Course registration
    # 3. Course Teaching Assignment
    # 4. Subject Teaching Assignment 
    
    self.subject_registrations.each do |subject_registration|
      subject_registration.deactivate
    end
    
    self.subject_teaching_assignments.each do |subject_teaching_assignment|
      subject_teaching_assignment.deactivate
    end
    
    self.is_active = false 
    self.save
  end
  
  
  def recover_subject
    self.subject_registrations.each do |subject_registration|
      subject_registration.re_activate
    end
    
    self.subject_teaching_assignments.each do |subject_teaching_assignment|
      subject_teaching_assignment.re_activate
    end
    
    self.is_active = true 
    self.save 
  end
  
  
  
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_filter :ensure_has_school_admin_role
  
  def index
    add_breadcrumb "Pick the subject", 'subjects_path'
    @active_subjects = current_user.get_managed_school.all_active_subjects
  end
  
  def new
    @new_subject  = Subject.new 
    @active_subjects = current_user.get_managed_school.all_active_subjects
  end
  
  def new_subject_teaching_assignment
    @school = current_user.get_managed_school
    @subjects = @school.all_active_subjects
    @teachers = @school.teachers
    add_breadcrumb "Pick the subject", 'new_subject_teaching_assignment'
  end
  
  def create
    @school = current_user.get_managed_school
    @subject = Subject.new(params[:subject])
    
    @starting_date = params[:subject][:starting_date]
    @ending_date = params[:subject][:starting_date]
    
    @subject.starting_date = parse_date(@starting_date) 
    @subject.ending_date = parse_date(@ending_date)
    
    @subject.school_id = @school.id
    @subject.term_id = params[:subject][:term_id]
    @subject.save
    
    redirect_to new_subject_url 
  end
  
  
  
  
=begin
  Managing the HISTORY 
  # assumption => current user is has_role?(:school_admin)
=end

  def active_subjects_management
    @school = current_user.get_managed_school
    @subjects = @school.all_active_subjects
    
    add_breadcrumb "Select the subject", 'active_subjects_management'
  end
  
  
  def passive_subjects_management 
    @school = current_user.get_managed_school
    @subjects = @school.all_passive_subjects
    add_breadcrumb "Select the subject", 'passive_subjects_management'
  end
  
  
  
  def duplicate_active_subject
    duplicate_subject(params)
  end
  
  def duplicate_passive_subject
    duplicate_subject(params)
  end
  
  def duplicate_subject(params)
    @subject = Subject.find_by_id(params[:subject_id])
    @clone_subject = @subject.clone 
    @school = current_user.get_managed_school
    @active_subjects = @school.all_active_subjects
    
    if @subject.is_active == true 
      add_breadcrumb "Select the subject", 'active_subjects_management'
      set_breadcrumb_for @subject, 'duplicate_active_subject_path' + "(#{@subject.id})", 
                  "Create Duplicate"
    else 
      add_breadcrumb "Select the subject", 'passive_subjects_management'
      set_breadcrumb_for @subject, 'duplicate_passive_subject_path' + "(#{@subject.id})", 
                  "Create Duplicate"
    end
    
    
  end
  
  def execute_duplicate_subject 
    @subject = Subject.new(params[:subject])
    @school =  current_user.get_managed_school
    @subject.school_id = @school.id 
    
    # parse the date T_T sigh.. 
    starting_date = params[:subject][:starting_date]
    ending_date  = params[:subject][:ending_date]
    # 02/29/2012
    
    @subject.starting_date = parse_date( starting_date)
    @subject.ending_date = parse_date ( ending_date ) 
   
    if @subject.save
      redirect_to active_subjects_management_url 
    else
      redirect_to duplicate_subject_url( @subject )
    end
  end
  
  def close_subject
    @subject = Subject.find_by_id( params[:entry_id])
    @subject.close_subject
  end
  
  def recover_subject
    @subject=  Subject.find_by_id( params[:entry_id])
    @subject.recover_subject 
  end
  
  

  protected
  def parse_date(date)
    date_data  = date.split("/")
    asked_date = Date.civil(date_data[2].to_i,   # year
                  date_data[0].to_i,   # month 
                    date_data[1].to_i )   # day 
                    
    return asked_date 
  end 
  
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/active_subjects_management.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Active Subjects", 
        "Manage the subjects: see the courses, duplicate the subject for new academic year, etc").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
 
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Subject</th>
            <th>Starting<br />yyyy-mm-dd</th>
            <th>Deadline<br />yyyy-mm-dd</th>
            <th>Total Courses</th>
            <th>Total Students</th>
            <th colspan="2">
              Action
            </th>
          </tr>
        </thead>
        <tbody>
          <% @subjects.each do |subject| %>
            <tr id="<%= "entry_row_" + subject.id.to_s %>">
              <td><%= subject.name %></td>
              <td><%= subject.starting_date %></td>
              <td><%= subject.ending_date %></td>
              <td><%= subject.courses.count %></td>
              <td><%= subject.students_count %></td>
              <td> 
                <%= link_to "Duplicate", duplicate_active_subject_url(subject), :class=> "btn btn-primary"%>
              </td>
              <td>
                <%= link_to "Close", '#', 
                          :class => "btn btn-danger entry-link entry-closer",
                          :id => "entry_#{subject.id}" %>
              </td>
            </tr>
          <% end %>
         
        </tbody>
      </table>
      
      
      
      <div class=" hidden" id="close-entry">
        <%= form_tag  close_subject_url  , :method => :post  do  %>
          <%= hidden_field_tag 'entry_id' , ''  %>
        <% end %>
      </div>
      

      
      
      
      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

app/views/subjects/close_subject.js.erb
$(document).ready(function(){
  $("#entry_<%= @subject.id %>").hideLoading();
  $("#entry_row_<%= @subject.id %>").remove();
});

app/views/subjects/duplicate_active_subject.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Duplicate Subjects", 
        "Modify the selected subject: change the starting and ending date, at least.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
 
  
  <div class="row-fluid">
    <div class="span8">


      <%= form_for @clone_subject  , :url => execute_duplicate_subject_url,
          :method => :post, :html => {:class => "form-horizontal"} do |f| %>



        <div class="control-group">
          <%= f.label :name, "Nama Pelajaran" %>
          <div class="controls">
            <%= f.text_field :name, :class=>"input-xlarge" %>
            <p class="help-block">Masukkan nama pelajaran.</p>
          </div>
        </div>
        
        
        
        <div class="control-group">
          <%= f.label :code, "Kode Pelajaran" %>
          <div class="controls">
            <%= f.text_field :code, :class=>"input-xlarge" %>
            <p class="help-block">Masukkan kode pelajaran (jika ada).</p>
          </div>
        </div>
        
        
        <div class="control-group">
          <%= f.label :starting_date, "Tanggal Mulai" %>
          <div class="controls">
            <%= f.text_field :starting_date, :value => "", :class=>"input-xlarge"  ,'data-datepicker'=>'datepicker'  %>
            <p class="help-block"></p>
          </div>
        </div>
        
        <div class="control-group">
          <%= f.label :ending_date, "Tanggal Selesai" %>
          <div class="controls">
            <%= f.text_field :ending_date, :value => "", :class=>"input-xlarge" ,'data-datepicker'=>'datepicker' %>
            <p class="help-block"></p>
          </div>
        </div>
        
        
        
        <div class="control-group">
          <%= f.label :description, "Deskripsi Pelajaran" %>
          <div class="controls">
            <%= f.text_area :description, :class=>"input-xlarge", :rows => 5 %>
            <p class="help-block">Masukkan deskripsi pelajaran.</p>
          </div>
        </div>



        <%= hidden_field_tag 'school_id', current_user.get_managed_school.id   %>


        <div class="form-actions">
          <button class="btn btn-primary" type="submit">Create Subject</button>
        </div>


      <% end %>
      
      
      

    </div><!--/span-->

    <div class="span4">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th>Total Active Subjects: <%= @active_subjects.count %></th></tr>
        </thead>
        <tbody>
          <% @active_subjects.each do |subject| %>
            <tr>
              <td><%= subject.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div><!--/span-->
    
  </div><!--/row-->
      
      
      
      
      
      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

app/views/subjects/duplicate_passive_subject.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Duplicate Subjects", 
        "Modify the selected subject: change the starting and ending date, at least.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
 
  
  <div class="row-fluid">
    <div class="span8">


      <%= form_for @clone_subject  , :url => execute_duplicate_subject_url,
          :method => :post, :html => {:class => "form-horizontal"} do |f| %>



        <div class="control-group">
          <%= f.label :name, "Nama Pelajaran" %>
          <div class="controls">
            <%= f.text_field :name, :class=>"input-xlarge" %>
            <p class="help-block">Masukkan nama pelajaran.</p>
          </div>
        </div>
        
        
        
        <div class="control-group">
          <%= f.label :code, "Kode Pelajaran" %>
          <div class="controls">
            <%= f.text_field :code, :class=>"input-xlarge" %>
            <p class="help-block">Masukkan kode pelajaran (jika ada).</p>
          </div>
        </div>
        
        
        <div class="control-group">
          <%= f.label :starting_date, "Tanggal Mulai" %>
          <div class="controls">
            <%= f.text_field :starting_date, :value => "", :class=>"input-xlarge"  ,'data-datepicker'=>'datepicker'  %>
            <p class="help-block"></p>
          </div>
        </div>
        
        <div class="control-group">
          <%= f.label :ending_date, "Tanggal Selesai" %>
          <div class="controls">
            <%= f.text_field :ending_date, :value => "", :class=>"input-xlarge" ,'data-datepicker'=>'datepicker' %>
            <p class="help-block"></p>
          </div>
        </div>
        
        
        
        <div class="control-group">
          <%= f.label :description, "Deskripsi Pelajaran" %>
          <div class="controls">
            <%= f.text_area :description, :class=>"input-xlarge", :rows => 5 %>
            <p class="help-block">Masukkan deskripsi pelajaran.</p>
          </div>
        </div>



        <%= hidden_field_tag 'school_id', current_user.get_managed_school.id   %>


        <div class="form-actions">
          <button class="btn btn-primary" type="submit">Create Subject</button>
        </div>


      <% end %>
      
      
      

    </div><!--/span-->

    <div class="span4">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr><th>Total Active Subjects: <%= @active_subjects.count %></th></tr>
        </thead>
        <tbody>
          <% @active_subjects.each do |subject| %>
            <tr>
              <td><%= subject.name %></td>
            </tr>
          <% end %>
        </tbody>
      </table>
      
    </div><!--/span-->
    
  </div><!--/row-->
      
      
      
      
      
      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

app/views/subjects/index.html.erb
<div class="span9 content">
  <%#= render :partial => "layouts/guide/index_client_loans", :locals => {:client => @client} %>

  <%#= render :partial => "payments/breadcrumb", :locals => {:client => @client, :loan => nil} %>
  
  
  
  <%= create_guide("New Course", 
        "First, select the subject which course you are about to add.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>

  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Subject Name</th>
            <th>Subject Code</th>
            <th>Term</th>
            <th>Total Course</th>
          </tr>
        </thead>
        <tbody>
          <% @active_subjects.each do |subject| %>
            <tr>
              <td><%= link_to "#{subject.name}", new_subject_course_url(subject) %></td>
              <td><%= subject.code %></td>
              <td>
                <% if not subject.term.nil?%>
                <%= subject.term.title  %>
                <% end%>
              </td>
              <td><%= subject.courses.count %></td>
            </tr>
          <% end %>


         
        </tbody>
      </table>

      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/subjects/new_subject_teaching_assignment.html.erb
<div class="span9 content">
  <%#= render :partial => "layouts/guide/index_client_loans", :locals => {:client => @client} %>

  <%#= render :partial => "payments/breadcrumb", :locals => {:client => @client, :loan => nil} %>
  
  
  
  <%= create_guide("Assign Subject Teacher", 
        "First, select the subject which teacher you are about to assign.").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>

  
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Subject Name</th>
            <th>Subject Code</th>
            <th>Total Course</th>
            <th>Teachers Assigned</th>
          </tr>
        </thead>
        <tbody>
          <% @subjects.each do |subject| %>
            <tr>
              <td><%= link_to "#{subject.name}", new_subject_subject_teaching_assignment_url(subject) %></td>
              <td><%= subject.code %></td>
              <td><%= subject.courses.count %></td>
              <td><%= subject.subject_teaching_assignments.count   %></td>
            </tr>
          <% end %>


         
        </tbody>
      </table>

      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

<%# content_for :additional_js  do %>
 
  <%#= javascript_include_tag "DT.js" %> 
  <%#= javascript_include_tag "DT_bootstrap.js" %> 
<%# end %>

app/views/subjects/passive_subjects_management.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Active Subjects", 
        "Manage the subjects: see the courses, duplicate the subject for new academic year, etc").html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
 
  <div class="row-fluid">
    <!-- <div class="span12"> -->
      
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        <thead>
          <tr>
            <th>Subject</th>
            <th>Starting<br />yyyy-mm-dd</th>
            <th>Deadline<br />yyyy-mm-dd</th>
            <th>Total Courses</th>
            <th>Total Students</th>
            <th colspan="2">
              Action
            </th>
          </tr>
        </thead>
        <tbody>
          <% @subjects.each do |subject| %>
            <tr id="<%= "entry_row_" + subject.id.to_s %>">
              <td><%= subject.name %></td>
              <td><%= subject.starting_date %></td>
              <td><%= subject.ending_date %></td>
              <td><%= subject.courses.count %></td>
              <td><%= subject.students_count %></td>
              <td> 
                <%= link_to "Duplicate", duplicate_passive_subject_url(subject), :class=> "btn btn-primary"%>
              </td>
              <td>
                <%= link_to "Recover", '#', 
                          :class => "btn btn-danger entry-link entry-recover",
                          :id => "entry_#{subject.id}" %>
              </td>
            </tr>
          <% end %>
         
        </tbody>
      </table>
      
      
      
      <div class=" hidden" id="close-entry">
        <%= form_tag  recover_subject_url  , :method => :post  do  %>
          <%= hidden_field_tag 'entry_id' , ''  %>
        <% end %>
      </div>
      

      
      
      
      
      
      
    <!-- </div> -->   <!--/span12-->
  </div><!--/row-->

</div><!--/span-->

app/views/subjects/recover_subject.js.erb
$(document).ready(function(){
  $("#entry_<%= @subject.id %>").hideLoading();
  $("#entry_row_<%= @subject.id %>").remove();
});