config/routes.rb
Debita46::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => "registrations"}
  
  resources :users 
  
  match 'dashboard'           => 'home#dashboard'  , :as => :dashboard
  root :to => 'home#dashboard'
  
  match 'raise_exception' => 'home#raise_exception', :as => :raise_exception 
  
  resources :terms   
  resources :enrollments
  resources :subjects do
    resources :courses 
    resources :subject_teaching_assignments
    resources :subject_registrations 
  end
  
  resources :courses do 
    resources :course_teaching_assignments
    resources :course_registrations
    resources :projects
    resources :groups
  end
  
  resources :projects
  resources :project_submissions
  resources :project_submissions do 
    resources :pictures
  end
  resources :user do 
    resources :project_submissions
  end
  
  resources :groups do 
    resources :group_memberships
  end
  resources :group_memberships
  
=begin
  CREATE SUBJECT, TERM_based
=end

  match 'select_term_to_create_subject' => 'terms#select_term_to_create_subject', :as => :select_term_to_create_subject
  match 'execute_close_term' => 'terms#execute_close_term', :as => :execute_close_term, :method => :post 
  match 'closed_terms' => 'terms#closed_terms', :as => :closed_terms
  
  
  match 'active_subjects_management' => "subjects#active_subjects_management", :as => :active_subjects_management
  match 'passive_subjects_management' => "subjects#passive_subjects_management", :as => :passive_subjects_management
  match 'duplicate_active_subject/:subject_id' => "subjects#duplicate_active_subject" , :as => :duplicate_active_subject
  match 'duplicate_passive_subject/:subject_id' => "subjects#duplicate_passive_subject" , :as => :duplicate_passive_subject
  
  match 'execute_duplicate_subject' => "subjects#execute_duplicate_subject" , :as => :execute_duplicate_subject, :method => :post 
  match 'close_subject' => "subjects#close_subject", :as => :close_subject, :method => :post 
  match 'recover_subject' => "subjects#recover_subject", :as => :recover_subject, :method => :post 
  
  match 'new_subject_teaching_assignment' => "subjects#new_subject_teaching_assignment", :as => :new_subject_teaching_assignment
  match 'pick_subject_for_course_teaching_assignment' => "courses#pick_subject_for_course_teaching_assignment", :as => :pick_subject_for_course_teaching_assignment
  match 'new_course_teaching_assignment/:subject_id' => "courses#new_course_teaching_assignment", :as => :new_course_teaching_assignment
  
  match 'select_course_for_grade_summary' => "courses#select_course_for_grade_summary", :as => :select_course_for_grade_summary 
  match 'show_student_grades_for_course/:course_id' => "courses#show_student_grades_for_course", :as => :show_student_grades_for_course 
  match 'show_project_grading_details/project/:project_id/student/:student_id' => "courses#show_project_grading_details", :as => :show_project_grading_details 
  
  
  
  match 'pick_subject_for_student_registrations' => "subject_registrations#pick_subject_for_student_registrations", :as => :pick_subject_for_student_registrations
  
  match 'select_subject_for_course_registration' => "course_registrations#select_subject_for_course_registration", :as => :select_subject_for_course_registration
  match 'select_course_for_course_registration/subject/:subject_id' => "course_registrations#select_course_for_course_registration", :as => :select_course_for_course_registration
  
  match 'new_teacher'           => 'enrollments#new_teacher'  , :as => :new_teacher
  match 'new_student'           => 'enrollments#new_student'  , :as => :new_student
  
  
  match 'select_active_project_for_admin' => "projects#select_active_project_for_admin", :as => :select_active_project_for_admin
  match 'gallery_mode_active_project/teacher/:teacher_id/project/:project_id' => "pictures#gallery_mode_active_project" , :as => :gallery_mode_active_project
  match 'view_submission_rate/:project_id' => 'projects#view_submission_rate', :as => :view_submission_rate
  match 'select_subject_for_project' => "projects#select_subject_for_project", :as => :select_subject_for_project
  match 'select_course_for_project/subject/:subject_id' => "projects#select_course_for_project", :as => :select_course_for_project
  match 'close_project' => "projects#close_project", :as => :close_project, :method => :post 
  match 'recover_project' => "projects#recover_project", :as => :recover_project, :method => :post 
  match 'past_projects' => "projects#past_projects", :as => :past_projects
  
  match 'select_active_project_to_be_edited' => "projects#select_active_project_to_be_edited", :as => :select_active_project_to_be_edited
  
  match 'select_subject_for_group' => "groups#select_subject_for_group", :as => :select_subject_for_group
  match 'select_course_for_group/subject/:subject_id' => "groups#select_course_for_group", :as => :select_course_for_group
  match 'select_group_for_group_leader' => "groups#select_group_for_group_leader", :as => :select_group_for_group_leader
  match 'select_group_leader/group/:group_id' => "groups#select_group_leader", :as => :select_group_leader, :method => :post
  match 'execute_select_group_leader' => "groups#execute_select_group_leader", :as => :execute_select_group_leader, :method => :post
  
  
  match 'select_subject_for_group_membership' => "group_memberships#select_subject_for_group_membership", :as => :select_subject_for_group_membership
  match 'select_course_for_group_membership/subject/:subject_id' => "group_memberships#select_course_for_group_membership", :as => :select_course_for_group_membership
  match 'select_group/course/:course_id' => "group_memberships#select_group", :as => :select_group
  
  
  match 'project_submissions_display' => "project_submissions#project_submissions_display", :as => :project_submissions_display
  match 'select_project_for_grading' => "projects#select_project_for_grading", :as => :select_project_for_grading
  match 'select_project_submission_for_grading/project/:project_id' => "project_submissions#select_project_submission_for_grading", :as => :select_project_submission_for_grading
  match 'show_submission_pictures_for_grading/project_submission/:project_submission_id' => "project_submissions#show_submission_pictures_for_grading", :as => :show_submission_pictures_for_grading
  match 'grade_project_submission_picture/picture/:picture_id' => "pictures#grade_project_submission_picture", :as => :grade_project_submission_picture
  match 'execute_grading/picture/:picture_id' => "pictures#execute_grading", :as => :execute_grading, :method => :post
  
  match 'gallery_mode_grading/project/:project_id' => "pictures#gallery_mode_grading" , :as => :gallery_mode_grading
  match 'gallery_picture_grading/project/:project_id/picture/:picture_id' => "pictures#gallery_picture_grading" , :as => :gallery_picture_grading
  match 'execute_grading_score/picture/:picture_id' => "pictures#execute_grading_score", :as => :execute_grading_score, :method => :post
  
  
  match 'select_project_to_publish_grade' => "projects#select_project_to_publish_grade", :as => :select_project_to_publish_grade
  match 'execute_publish_grade' => "projects#execute_publish_grade", :as => :execute_publish_grade, :method => :post 
=begin
  FOR STUDENTS 
=end  
  match 'student_projects' => "projects#student_projects", :as => :student_projects
  
  match 'project_submissions/:project_submission_id/create_revision/:original_pic_id' => "pictures#create_revision", :as => :create_revision
  
  resources :pictures do 
    resources :positional_comments
    resources :comments
  end
  
  match 'first_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_first_child_comment", :as => :create_first_child_comment
  match 'create_child_comment/picture/:picture_id/comment/:root_comment_id' => "comments#create_child_comment", :as => :create_child_comment
  match 'delete_original_image' => "pictures#delete_original_image", :as => :delete_original_image , :method => :post
  match 'delete_image_from_show' => "pictures#delete_image_from_show", :as => :delete_image_from_show , :method => :post
  
  
  
  
  
  match 'timezone_setup' => 'schools#timezone_setup', :as => :timezone_setup 
  match 'execute_timezone_setup' => 'schools#execute_timezone_setup', :as => :execute_timezone_setup, :method => :post 
  
  
  match 'delivery_method_setup' => 'schools#delivery_method_setup', :as => :delivery_method_setup 
  match 'execute_delivery_method_setup' => 'schools#execute_delivery_method_setup', :as => :execute_delivery_method_setup, :method => :post
  
  
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
  
  

end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_accepted_submission.html.erb
<table cellpadding="0" cellspacing="0" border="0" 
      class="table table-striped table-bordered" id="approval_status">
  <tbody>
    <tr>
      <td style="text-align:center;">
        <button href="#" class=" btn btn-success">ACCEPTED</button>
      </td>
    </tr>
  </tbody>
</table>

app/views/pictures/_download_original.html.erb
<table cellpadding="0" cellspacing="0" border="0" 
      class="table table-striped table-bordered" id="example">
  <tbody>
    <tr>
      <td style="text-align:center;">
        <%= link_to "Download Original", "#{picture.original_image_url}", 
              :class => "btn btn-large btn-primary"%>
      </td>
    </tr>
  </tbody>
</table>

app/views/pictures/_gallery_grading_revision_list.html.erb
<h3>Revision List</h3>

<ul class="thumbnails">
  
  <% all_revisions.each do |revision| %>
  <li class="span6">
    <%= link_to gallery_picture_grading_path(project,revision) + "?gallery_pic_id=#{project_submission.id}",
            :class => "thumbnail #{class_for_current_displayed_revision(revision, current_display)}" do %>
      <%#= image_tag revision.revision_image_url %> 
      <%= image_tag revision.get_icon("revision") %>
    <% end %>
    <p>
      <%= get_picture_status_label(revision).html_safe %>
    
    </p>
  </li>
  <% end %>


  

</ul>
  

app/views/pictures/_grading_revision_list.html.erb
<h3>Revision List</h3>

<ul class="thumbnails">
  
  <% all_revisions.each do |revision| %>
  <li class="span6">
    <%= link_to grade_project_submission_picture_url(revision),
            :class => "thumbnail #{class_for_current_displayed_revision(revision, current_display)}" do %>
      <%#= image_tag revision.revision_image_url %> 
      <%= image_tag revision.get_icon("revision") %>
    <% end %>
    <p>
      <b><%= revision.name %></b>
    </p>
  </li>
  <% end %>


  

</ul>
  

app/views/pictures/_image_viewer.html.erb
<h3> <%= @picture.name %></h3>
<h4> Uploaded on: <%= @picture.upload_datetime_local(@school) %></h4>
<% if @picture.is_original == true  %>
  <span class="label">Original Submission</span>
<% else %>
	<span class="label label-success">Revision Submission</span>
<% end %>
<hr />


<!-- The navigation element (<= Prev)  and (Next =>)-->
<ul class="pager">
      <%= get_previous_project_picture(@picture, false, false ).html_safe %>
      <%= get_next_project_picture(@picture, false, false).html_safe %>
</ul>


<!-- The image in display -->
<div class="thumbnail image display_image_wrapper "id="display_wrapper" >
  
  <%#= render :partial => "pictures/positional_comment_form", 
                  :locals => {:picture => @picture}%>

  
  
  <%= image_tag @picture.display_image_url,  
        :style => "width:590px;" , :id => "display_image" %>
        
  <!-- render all the positional_comment -->
  <%= render :partial => "pictures/feedback_map", :locals => {:picture => @picture }%>
</div>

<!-- The cropper -->
<div class="thumbnail image display_image_wrapper" id="cropper_wrapper" >
  
  <%= render :partial => "pictures/positional_comment_form", 
                  :locals => {:picture => @picture}%>

  
  
  <%= image_tag @picture.display_image_url,  
        :style => "width:590px;", :id => "target" %>
        
  <!-- render all the positional_comment -->
  <%= render :partial => "pictures/feedback_map", :locals => {:picture => @picture }%>
</div>



<hr />

app/views/pictures/_new_picture_upload.html.erb
<%= form_for @new_picture, :url => project_submission_pictures_url(@project_submission) , 
          :html => {:class=> "well form-search",
            :id => 'upload_picture' }  do |f| %>
  <%= hidden_field_tag 'is_original', 
          ORIGINAL_PICTURE  %>
  <% tranloadit_array = transloadit_with_max_size('potoschool_store_image', 1) %>
  <%= hidden_field_tag 'picture_filetype', 
          PICTURE_FILETYPE[:image]  %>
  <%#= transloadit :potoschool_store_image, { :auth => {:max_size => 2000}}  %>
  <%= hidden_field_tag 'params',  tranloadit_array[0]  %>
  <%= hidden_field_tag 'signature',  tranloadit_array[1]  %>
          
  <%#= f.file_field :original_image_url, :class => "input-medium search-query transloadit-input" , 
            :multiple => "multiple", :style=>"width:200px;" %>
  <%= f.file_field :original_image_url, :class => "input-medium search-query transloadit-input" , 
             :style=>"width:200px;" %>
            <br />
            <br />
            
            <!-- params    = Transloadit::Rails::Engine.template(template, options).to_json -->
            
            
  <button type="submit" class=" hide btn submit-button">Upload</button>
  <p class="help">You can upload  images one by one.</p>
  <p class="help feedback">
    If your image file size is bigger than <b>1 MB</b>,
    you can resize it by using Photoshop or other image editing file.<br />
    Here is the tutorial to resize image using Photoshop: <%= link_to "CLICK HERE", 
    "http://s3.amazonaws.com/potoschool_icon/TUTORIAL+PHOTO+RESIZE.pdf" %>
  </p>

<% end %>

app/views/pictures/_no_student_activities_notification.html.erb
<% reasons = [] %>
<% current_time = Time.now.to_datetime %>

<% if  not project.in_between_starting_and_deadline_time? %>
  <% if project.earlier_than_starting_time?(current_time )%>
    <% reasons << "Project has not started: #{project.get_starting_datetime_local_time}"%>
  <% elsif  project.later_than_deadline_time?(current_time ) %>
   <% reasons << "Deadline has passed: #{project.get_deadline_datetime_local_time}"%>
  <% end %>
<% end %>


<% if project.is_closed? %>
  <% reasons << "The project is closed" %>
<% end %>

<div class="alert alert-error">
  <strong>No activities allowed.</strong> 
     

  <% if reasons.length > 0 %>
    <ol>
      <% reasons.each do |reason| %>
        <li><%= reason %></li>
      <% end %>
    </ol>
  <% end %>
  
</div>

app/views/pictures/_root_comment.html.erb
<li class="root_comment clearfix" id="root_comment_element-<%= root_comment.id %>">
  <a href="#" class="thumbnail avatar-wrapper" style="text-align:center;" >
    <img  src="<%= DEFAULT_PROFILE_PIC_URL %>" class="avatar" >
  </a>

  <div class="particulars">
    <div class="name" > <%= root_comment.user.name %>
      <% if root_comment.user.has_role?(:student)%>
        <span class="label">Student</span>
      <% elsif root_comment.user.has_role?(:teacher) %>
        <span class="label label-info">Teacher</span>
      <% end %>
      
    </div>
    
    <blockquote>
      <p><%= root_comment.body%></p>
    </blockquote>
    
    <% if not root_comment.has_children? %>
      <%= render :partial => "pictures/first_child_comment_wrapper", 
                :locals => {
                  :picture => picture, 
                  :root_comment => root_comment
                }%>
      
    <% else %>
    <!--  create the child comment list -->
      <%= render :partial => "pictures/child_comment_wrapper",  
                  :locals => {
                    :root_comment => root_comment,
                    :picture => picture
                  } %>
    
    <% end %>
    
    
    
  </div>  <!-- End of div.particulars-->
  <br />
</li>

app/views/pictures/_student_activities.html.erb
<% if @picture.picture_filetype == PICTURE_FILETYPE[:image]  %>
  <p style="text-align:center;">
    <button data-toggle="button" id="pilipoto-switcher" 
      class="btn btn-primary waitMode">Turn On Feedback Mode</button>
  </p>
  <hr />
<% end %>

<% if current_user.is_submission_owner?(@project_submission) %>
<!-- if it is not approved, revision still can be uploaded  -->
  <% if @original_picture.can_upload_revision? %>
    <% if @picture.picture_filetype == PICTURE_FILETYPE[:image] %>
      <%= render :partial => "pictures/upload_picture_revision_form"%>
    <% end %>
    
    <% if @picture.picture_filetype != PICTURE_FILETYPE[:image] %>
      <%= render :partial => "pictures/upload_document_revision_form"%>
    <% end %>
  <% end %>
<% end %>

app/views/pictures/_submitted_picture_display.html.erb
<li class="span3">
  <div class="thumbnail">
    
   
    
    <% if  original_picture.any_picture_submission_approved? %>
      <%= link_to  project_submission_picture_url( project_submission, original_picture.approved_picture ),
          :class => "thumbnail" , :style => "height:160px; overflow:hidden;" do %>
        <%= image_tag original_picture.approved_picture.get_icon("index") %>
      <% end %>
    <% else %>
      <%= link_to  project_submission_picture_url( project_submission, picture.last_revision),
       :class => "thumbnail" , :style => "height:160px; overflow:hidden;" do %>
        <%= image_tag picture.last_revision.get_icon("index") %>
      <% end %>
    <% end %>
    
    
    <!-- <img alt="" src="http://placehold.it/260x180"> -->
    <div class="caption">
      <table cellpadding="0" cellspacing="0" border="0" 
            class="table table-striped table-bordered" id="example">
        
        <tbody>
          
            <tr>
              <td colspan="2" style="overflow:hidden;">
                <b><%= original_picture.name[0..20] %></b>
              </td>
            </tr>
          
          <tr>
            <td>Revisions</td>
            <td><%= original_picture.revisions.where(:is_deleted => false ).count %></td>
          </tr>
          
            <% if original_picture.any_picture_submission_approved? %>
            <tr>
              <td>Approval</td>
              <td>YES</td>
            </tr>
            <tr>
              <td>Score</td>
              <td><%= original_picture.approved_picture.score %></td>
            </tr>
            <% else %>
              <% if original_picture.last_revision.is_approved == false %>
                <tr>
                  <td>Approval</td>
                  <td>REJECT</td>
                </tr>
                <tr>
                  <td>Score</td>
                  <td>0</td>
                </tr>
              <% else %>
                <tr>
                  <td>Approval</td>
                  <td>PENDING</td>
                </tr>
                <tr>
                  <td>Score</td>
                  <td>Pending</td>
                </tr>
              <% end %>
            <% end %>
            
            <tr>
              <td colspan="2" style="text-align:center;">
                <% if original_picture.can_be_deleted?  %>
                  <%= form_for original_picture, 
                        :url => delete_original_image_url,
                        :html => {:class => "delete_pic" } do |f| %>
                    <%= hidden_field_tag 'picture_id', original_picture.id  %>
                    <button href="#" class="btn btn-danger delete_original" >
                      Delete
                    </button>
                  <% end %>
                  
                <% else %>
                  --
                <% end %>
              </td>
            </tr>
         </tbody>
      </table>
     
    </div>
     
     
        
      
  </div>
</li>

app/views/pictures/_upload_picture_revision_form.html.erb
<h3>Upload Revision</h3>


<%= form_for Picture.new, :url => project_submission_pictures_url(@project_submission) , 
          :html => {:class=> "well form-search",
            :id => 'upload_picture_revision' }  do |f| %>
  <%= hidden_field_tag 'is_original', 
          REVISION_PICTURE  %>
  <%= hidden_field_tag 'picture_filetype', 
          PICTURE_FILETYPE[:image]  %>
  <%#= transloadit :potoschool_store_image %>
  <% tranloadit_array = transloadit_with_max_size('potoschool_store_image', 5) %>
  <%= hidden_field_tag 'params',  tranloadit_array[0]  %>
  <%= hidden_field_tag 'signature',  tranloadit_array[1]  %>
  <%= f.file_field :original_image_url, :class => "input-medium search-query transloadit-input" , 
             :style=>"width:200px;" %>
            <br />
  <%= hidden_field_tag 'original_picture_id', 
          @picture.original_picture.id  %>
           
  <button type="submit" class=" hide btn submit-button">Upload Revision</button>
  <p class="feedback"></p>
  
<% end %>

<hr />

app/views/pictures/_uploader.html.erb
<ul class="nav nav-tabs">
  <li class="active"><a href="#image_tab" data-toggle="tab">Upload Image</a></li>
  <li><a href="#document_tab" data-toggle="tab">Upload Document</a></li>
</ul>

<div class="tab-content" id="tab_content_wrapper" style="display:none;">
  <div class="tab-pane active" id="image_tab">
    <%= render :partial => "pictures/new_picture_upload" %>
  </div>
  <div class="tab-pane" id="document_tab">
    <%= render :partial => "pictures/new_document_upload" %>
  </div>
</div>

<% content_for :additional_js do %>
  <script type="text/javascript" src="//assets.transloadit.com/js/jquery.transloadit2.js"></script>
  <script type="text/javascript">
     // We call .transloadit() after the DOM is initialized:
     $(document).ready(function() {
       $('#upload_picture').transloadit({
         wait : true, 
         pollTimeout : 15000,
         processZeroFiles : false,
         onStart : function(assembly){
           $("#tab_content_wrapper").fadeOut();
           $("#uploading_progress_notification").fadeIn();
           action_tracker_status = 1 ;
         },
         onCancel: function(){
           $("#uploading_progress_notification").hide();
           $("#refreshing_progress_notification").fadeIn();
           window.location.reload(true);
         }
       });
     
       $('#upload_document').transloadit({
          wait : true, 
          pollTimeout : 15000,
          processZeroFiles : false,
          onStart : function(assembly){
             $("#tab_content_wrapper").fadeOut();
             $("#uploading_progress_notification").fadeIn();
             action_tracker_status = 1 ;
          },
          onCancel: function(){
            $("#uploading_progress_notification").hide();
            $("#refreshing_progress_notification").fadeIn();
            window.location.reload(true);
          }
        });
     });
  </script>
<% end %>

app/views/pictures/gallery_mode_active_project.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Gallery Mode", 
        "Project: <b> #{@project.title}</b>" + "<br />" + 
        "Course: #{@project.course.name}"  + "<br />" + 
        "Subject: #{@project.course.subject.code}" + "<br />" + 
        "Deadline: #{@project.deadline_datetime.in_time_zone("Jakarta")}" + "<br />" +  
        "Total Student: <b>#{@project.project_submissions.count }</b> "+ "<br />" +
        "Completed: <b>#{@project.completion_rate }</b> " + "<br />" + 
        "Submission quota: <b>#{@project.total_submission }</b> " ) .html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  <hr />
  
  
  <!-- display the uploaded image here!  -->
 
    <div class="span12">
      <ul class="thumbnails" id="uploaded_image_container">
        
        <% @project_submissions.each do |project_submission| %>
          <% if project_submission.pictures.count == 0 %>
            <% next %>
          <% end %>
          <% pictures = project_submission.original_pictures.order("created_at DESC") %>
          <!-- rendering the pics -->
          <% pictures.each do |picture| %>
            <% if picture.picture_filetype == PICTURE_FILETYPE[:image]%>
              <%= render :partial => "pictures/gallery_mode_picture_display" , :locals => {
                :picture => picture,
                :original_picture => picture.original_picture , 
                :project_submission => project_submission,
                :project => @project
              }%>
            <% end %>
          <% end %>
        <% end %>
        
        
      </ul>
    </div>
  
</div><!--/span-->




<div class="modal" id="myModal" style="display:none;">
  <div class="modal-header">
  </div>
  <div class="modal-body">
    <p>
      <img src='' id="modalImage" />
    </p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn modal-closer">Close</a>
    <a href="#" class="btn btn-primary details-viewer">See Details</a>
  </div>
</div>



<% content_for :additional_js  do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".gallery_thumbnail").live('click', function(){
        
        var pic_id = $(this).attr("id").split("_")[1];
        var displayImageUrl = $("#pic_"+pic_id).text();
        // alert("thedisplay: " + displayImageUrl);
        
        summonGalleryModalHTML(displayImageUrl,"myModal");
       
        
        return false ;
      });
    });
  </script>
<% end %>

app/views/pictures/gallery_mode_grading.html.erb
<div class="span9 content">
  
  
  <%= create_guide("Gallery Mode", 
        "Select the submission to be graded in project: <b> #{@project.title}</b>" + "<br />" + 
        "Course: #{@project.course.name}"  + "<br />" + 
        "Subject: #{@project.course.subject.code}" + "<br />" + 
        "Deadline: #{@project.deadline_datetime.in_time_zone("Jakarta")}" + "<br />" +  
        "Total Student: <b>#{@project.project_submissions.count }</b> "+ "<br />" +
        "Completed: <b>#{@project.completion_rate }</b> " + "<br />" + 
        "Submission quota: <b>#{@project.total_submission }</b> " ) .html_safe %>
  
  <%= create_breadcrumb(@breadcrumbs).html_safe %>
  
  
  
  <!-- display the uploaded image here!  -->
    
    <%# cache( "gallery_grading_list_#{@project.id}" )  do %>
      <div class="span12">
        <% @project_submissions.each do |project_submission| %>
          
            <%# if project_submission.pictures.count == 0 %>
              <%# next %>
            <%# end %>
          <% cache( "gallery_grading_list_project_submission_#{project_submission.id}" )  do %> 
            <% user = project_submission.user %>
            <h3 style="margin-bottom:20px;" id="project_submission-<%= project_submission.id %>">
              <%= user.name %> | <%= user.nim %> 
            </h3>
            <ul class="thumbnails" >
              <% pictures = project_submission.original_pictures.order("created_at DESC") %>
              <!-- rendering the pics -->
              <% pictures.each do |picture| %>
                <% if picture.picture_filetype == PICTURE_FILETYPE[:image]%>
                  <%= render :partial => "pictures/gallery_mode_picture_display" , :locals => {
                    :picture => picture,
                    :original_picture => picture , 
                    :project_submission => project_submission,
                    :project => @project
                  }%>
                <% end %>
              <% end %>

            </ul>
    
            <hr />
          <% end %>  <!-- end of caching -->
    
        <% end %>
      </div>
    <%# end %>
    
    
  
</div><!--/span-->




<div class="modal" id="myModal" style="display:none;">
  <div class="modal-header">
  </div>
  <div class="modal-body">
    <p>
      <img src='' id="modalImage" />
    </p>
  </div>
  <div class="modal-footer">
    <a href="#" class="btn modal-closer">Close</a>
    <a href="#" class="btn btn-primary details-viewer">Grading</a>
  </div>
</div>



<% content_for :additional_js  do %>
  <script type="text/javascript">
    $(document).ready(function(){
      $(".gallery_thumbnail").live('click', function(){
        
        var pic_id = $(this).attr("id").split("_")[1];
        var displayImageUrl = $("#pic_"+pic_id).text();
        // alert("thedisplay: " + displayImageUrl);
        
        summonGalleryModalHTML(displayImageUrl,"myModal");
       
        
        return false ;
      });
    });
  </script>
<% end %>